change protoc-gen-go path

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -40,7 +40,12 @@ jobs:
     - name: Install protoc-gen-go
       run: |
         go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
-        echo "$GOPATH/bin" >> $GITHUB_ENV
+        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
+        echo "PATH=$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV
+
+    - name: Check protoc-gen-go Installation
+      run: |
+        protoc-gen-go --version || echo "protoc-gen-go not found"
 
     - name: Generate Code
       run: |
